services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./journal:/var/www/html
    ports:
      - 8888:80
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: journal
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
    ports:
      - 8887:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8886:8080

